### ISSUE TITLE
Add options to pass to the players

### ISSUE THREAD

**Issue by dummys** [awlnx/JimThePlayerLauncher#16]
Hi,

Is it possible to add an options to add our own options before calling the player ?
Like this plugin for firefox: https://addons.mozilla.org/fr/firefox/addon/watch-with-mpv/
For example on linux I use bumblebee in order to not use the nvidia gfx card for daily use, but for video I use it with optirun.
With this option I can say that the binary is optirun and then pass /usr/bin/mpv --force-window=immediate %%url%%
Thanks.
Cheers,
Jon

**Comment by awlnx** [comment]
should be fixed in staging. you can now do optirun,/usr/bin/mpv,--force-window=immediate and the extension will drop in the url itself. alternatively I could make this a lot nicer by turning on shell access.  this would mean that the input would be unsanitized I'm not sure if it would make the extension less secure as it more or less gives you indirect access to the shell through this command.
