### ISSUE TITLE
add option to pass all or some  youtube-dl links directly to the player

### ISSUE THREAD

**Issue by Scias** [awlnx/JimThePlayerLauncher#5]
The youtube workaround in background.js (from line 83) prevents it to work on other youtube-dl supported websites. (such as Twitch, Dailymotion...)
Removing or commenting out the workaround and just leaving Link = tab.url; fixes the issue. Example :

```
           // temporary workaround for youtube for players with youtube-dl
        // TODO 
        // *setup options page with a whitelist for special site workarounds
            //if (/.*youtube.*/.test(tab.url)) {
                Link = tab.url;

            //} else {
            //    Link = (this.linkshash[this.activetabid])[0];
            //}

```

But surely there was a reason for the workaround in the first place ?

**Comment by awlnx** [comment]
by default it just tries to grab a media link out of a get request. This works well for a large number of websites.

**Comment by awlnx** [comment]
Just to clarify the reason why this didn't/doesn't work on These site is because for all other sites it trys to use chrome's webrequest api to grab video links by their content-type such as x-video/flv.
this works for what I've tested all most all streaming sites. Expect the really really big ones like twitch or youtube who have special video encoding/formatting.
